# .github/workflows/update-activity.yml:

name: Update GitHub Activity

on:
  schedule:
    - cron: "*/30 * * * *" # Runs every 30 minutes
  workflow_dispatch: # Allows manual triggering

jobs:
  update-activity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update GitHub Activity
        uses: TheDanniCraft/activity-log@1
        with:
          GITHUB_USERNAME: "Leo041192"
          GITHUB_TOKEN: ${< secrets.ACTIONSECRET2024 }}
          TARGET_REPOS: '[team-leoooo/workout]'
          EVENT_LIMIT: '100'
